# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('secondName', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.People'),
        ),
    ]
